services:
  backend:
    build:
      context: ./backend
    env_file:
      - path: .env.example
        required: true
      - path: .env
        required: false
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
